[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "rkstool"
version = "1.1.2"
requires-python = ">=3.10"
readme = "README.md"
dependencies = []

[project.urls]
Source = "https://github.com/RyougiKukoc/rkstool"

[tool.hatch.build.targets.wheel]
packages = ["rkstool"]

[tool.hatch.build.targets.sdist]
include = ["/rkstool", "/pyproject.toml", "/README.md"]
